name: Regression and Unit Testing

on:
    push:
        branches:
            - 'develop'
            - 'master'
    workflow_call:
        inputs:
            runner:
                description: 'The github runner to use'
                default: 'ubuntu-latest'
                required: false 
                type: string 

jobs:
    print-tag:
        runs-on: ubuntu-latest
        steps:
        - name: "install stuff"
          run: apt-get update && apt-get install -y git python3 python3-numpy
        - name: "install more stuff"
          run: update-alternatives --install /usr/bin/python python /usr/bin/python3 10