name: Regression and Unit Testing

on:
    push:
        branches:
            - 'develop'
            - 'main'
    workflow_call:
        inputs:
            runner:
                description: 'The github runner to use'
                default: 'ubuntu-latest'
                required: false 
                type: string 

jobs:
    print-tag:
        runs-on: ${{inputs.runner || 'ubuntu-latest'}}$
        steps:
        - name: "Print the input tag to STDOUT"
          run: echo  'hi'


